baseURL = 'https://kajjabe.github.io/'
languageCode = 'fr-fr'
title = 'Shingsi'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    showCodeCopyButtons = true

[params.homeInfoParams]
    Title = "Salut, c'est Shingsi \U0001F44B"
    Content = "Bienvenue sur mon blog. Ici je partage mes aventures en cybersécurité."

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20