baseURL = 'https://kajjabe.github.io/shingsi/'
languageCode = 'fr-fr'
title = 'Shingsi'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    showCodeCopyButtons = true

[params.homeInfoParams]
    Title = "Bienvenue"
    Content = "Rapports, cheatsheet et retours d'expérience liés au domaine de la cyber"

[[menu.main]]
    name = "Rapports"
    url = "/rapports/"
    weight = 10

[[menu.main]]
    name = "Cheatsheet"
    url = "/cheatsheet/"
    weight = 10

[[menu.main]]
    name = "Projets"
    url = "/projets/"
    weight = 10

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20